export const TEMPLATES = [
  {
    id: 'corporate-onboarding',
    name: 'Bienvenida al Equipo (Grid Logo + Tabla)',
    description: 'Cabecera con logo a la izquierda y texto a la derecha, junto con una tabla estilizada de credenciales y accesos para nuevos miembros.',
    subject: '🎉 ¡Bienvenido(a) a NovaTech! Credenciales de acceso y bienvenida oficial',
    globalSettings: {
      backgroundColor: '#f1f5f9',
      contentBackgroundColor: '#ffffff',
      contentWidth: '600px',
      borderRadius: '16px',
      textColor: '#1e293b',
      padding: '36px',
    },
    blocks: [
      {
        id: 'tmpl-grid-1',
        type: 'grid',
        data: {
          layout: '30-70',
          verticalAlign: 'middle',
          gap: '16px',
          backgroundColor: 'transparent',
          borderRadius: '0px',
          paddingTop: '8px',
          paddingBottom: '16px',
          paddingLeft: '0px',
          paddingRight: '0px',
          leftType: 'image',
          leftImage: {
            url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
            alt: 'Logo NovaTech',
            width: '90px',
            maxWidth: '110px',
            borderRadius: '10px',
            alignment: 'center',
            linkUrl: '',
          },
          rightType: 'text',
          rightText: {
            heading: 'NovaTech Solutions',
            headingSize: '22px',
            headingColor: '#0f172a',
            content: 'Plataforma de Innovación Digital y Servicios Cloud.',
            textColor: '#475569',
            fontSize: '14px',
            lineHeight: '1.5',
            alignment: 'left',
          },
        },
      },
      {
        id: 'tmpl-div-1',
        type: 'divider',
        data: {
          color: '#e2e8f0',
          thickness: '1px',
          style: 'solid',
          paddingTop: '10px',
          paddingBottom: '16px',
          width: '100%',
        },
      },
      {
        id: 'tmpl-head-1',
        type: 'heading',
        data: {
          content: '¡Te damos una cordial bienvenida a nuestro equipo!',
          fontSize: '24px',
          fontWeight: '800',
          color: '#0f172a',
          textAlign: 'left',
          paddingTop: '4px',
          paddingBottom: '8px',
        },
      },
      {
        id: 'tmpl-text-1',
        type: 'text',
        data: {
          content: 'Estimado(a) colaborador(a), es un verdadero gusto darte la bienvenida a nuestra compañía. Para comenzar tus actividades de forma fluida, a continuación te proporcionamos tus **credenciales de acceso** a nuestras plataformas y redes corporativas:',
          fontSize: '15px',
          fontWeight: '400',
          color: '#334155',
          textAlign: 'left',
          lineHeight: '1.6',
          paddingTop: '4px',
          paddingBottom: '14px',
        },
      },
      {
        id: 'tmpl-table-1',
        type: 'table',
        data: {
          theme: 'modern',
          headers: ['Servicio / Plataforma', 'Usuario / Acceso', 'Clave Asignada'],
          rows: [
            ['Red Wi-Fi Oficinas', 'NovaTech_Team', '**Segura2026**'],
            ['Correo Corporativo', 'usuario@novatech.io', '**Temporal#2026**'],
            ['Portal Interno & Slack', 'novatech.slack.com', '**ConfigurarEnPrimerIngreso**'],
          ],
          headerBgColor: '#0f172a',
          headerTextColor: '#ffffff',
          rowBgColor: '#ffffff',
          altRowBgColor: '#f8fafc',
          textColor: '#334155',
          borderColor: '#e2e8f0',
          borderWidth: '1px',
          borderRadius: '12px',
          cellPadding: '12px 16px',
          textAlign: 'left',
          fontSize: '13px',
          headerFontSize: '13px',
          headerFontWeight: '700',
          paddingTop: '10px',
          paddingBottom: '18px',
          striped: true,
        },
      },
      {
        id: 'tmpl-btn-1',
        type: 'button',
        data: {
          text: 'Ingresar al Portal de Colaboradores →',
          url: 'https://novatech.io',
          backgroundColor: '#2563eb',
          textColor: '#ffffff',
          borderRadius: '12px',
          fontSize: '15px',
          fontWeight: '700',
          paddingX: '32px',
          paddingY: '14px',
          alignment: 'center',
          fullWidth: false,
          boxShadow: '0 4px 14px 0 rgba(37, 99, 235, 0.35)',
        },
      },
    ],
  },
  {
    id: 'youtube-showcase',
    name: 'Lanzamiento con Video de YouTube',
    description: 'Plantilla moderna diseñada para destacar nuevos videos, lanzamientos de productos o anuncios importantes.',
    globalSettings: {
      backgroundColor: '#0f172a',
      contentBackgroundColor: '#1e293b',
      contentWidth: '600px',
      borderRadius: '20px',
      textColor: '#f8fafc',
      padding: '36px',
    },
    blocks: [
      {
        id: 'block-1',
        type: 'heading',
        data: {
          content: '✨ ¡Nuevo episodio ya disponible!',
          fontSize: '28px',
          fontWeight: '800',
          color: '#ffffff',
          textAlign: 'center',
          paddingTop: '8px',
          paddingBottom: '4px',
        },
      },
      {
        id: 'block-2',
        type: 'text',
        data: {
          content: 'Descubre en este video cómo transformar el diseño de tus correos electrónicos utilizando componentes modulares y videos interactivos.',
          fontSize: '15px',
          fontWeight: '400',
          color: '#94a3b8',
          textAlign: 'center',
          lineHeight: '1.6',
          paddingTop: '4px',
          paddingBottom: '16px',
        },
      },
      {
        id: 'block-3',
        type: 'youtube',
        data: {
          url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
          title: 'Aprende a Diseñar Mails que Convierten',
          caption: 'Haz clic en el reproductor para ver la guía completa paso a paso en YouTube.',
          buttonText: 'Ver Video en YouTube ▶',
          cardBackground: '#0b1120',
          textColor: '#ffffff',
          borderRadius: '14px',
          paddingTop: '12px',
          paddingBottom: '20px',
        },
      },
      {
        id: 'block-4',
        type: 'box',
        data: {
          backgroundColor: '#334155',
          borderRadius: '12px',
          borderWidth: '1px',
          borderColor: '#475569',
          borderStyle: 'solid',
          paddingTop: '18px',
          paddingBottom: '18px',
          paddingLeft: '20px',
          paddingRight: '20px',
          children: [
            {
              id: 'box-c-1',
              type: 'heading',
              data: {
                content: '💡 Puntos clave incluidos en el video:',
                fontSize: '17px',
                fontWeight: '700',
                color: '#38bdf8',
                textAlign: 'left',
                paddingTop: '0px',
                paddingBottom: '8px',
              },
            },
            {
              id: 'box-c-2',
              type: 'text',
              data: {
                content: '• Cómo estructurar correos usando tablas responsivas sin romperse en Outlook.\n• Optimización de miniaturas y fallback para clientes sin soporte de iframe.\n• Aumento del CTR en más de un 40% al añadir un llamado a la acción visible.',
                fontSize: '14px',
                fontWeight: '400',
                color: '#cbd5e1',
                textAlign: 'left',
                lineHeight: '1.7',
                paddingTop: '0px',
                paddingBottom: '0px',
              },
            },
          ],
        },
      },
      {
        id: 'block-5',
        type: 'button',
        data: {
          text: '🚀 Probar PrettierMails Gratis',
          url: 'https://github.com',
          backgroundColor: '#6366f1',
          textColor: '#ffffff',
          borderRadius: '10px',
          fontSize: '16px',
          fontWeight: '700',
          paddingX: '32px',
          paddingY: '14px',
          alignment: 'center',
          fullWidth: false,
        },
      },
      {
        id: 'block-6',
        type: 'divider',
        data: {
          color: '#334155',
          thickness: '1px',
          style: 'solid',
          paddingTop: '20px',
          paddingBottom: '16px',
          width: '100%',
        },
      },
      {
        id: 'block-7',
        type: 'social',
        data: {
          alignment: 'center',
          youtube: 'https://youtube.com',
          twitter: 'https://twitter.com',
          github: 'https://github.com',
          instagram: 'https://instagram.com',
          paddingTop: '8px',
          paddingBottom: '12px',
        },
      },
      {
        id: 'block-8',
        type: 'text',
        data: {
          content: 'Has recibido este correo porque estás suscrito a nuestras novedades de diseño. Si no deseas recibir más correos, puedes desuscribirte aquí.',
          fontSize: '12px',
          fontWeight: '400',
          color: '#64748b',
          textAlign: 'center',
          lineHeight: '1.5',
          paddingTop: '8px',
          paddingBottom: '0px',
        },
      },
    ],
  },
  {
    id: 'welcome-onboarding',
    name: 'Bienvenida & Tutorial',
    description: 'Perfecta para recibir nuevos usuarios, explicar los primeros pasos e incluir un tutorial interactivo.',
    globalSettings: {
      backgroundColor: '#f8fafc',
      contentBackgroundColor: '#ffffff',
      contentWidth: '600px',
      borderRadius: '16px',
      textColor: '#1e293b',
      padding: '36px',
    },
    blocks: [
      {
        id: 'w-1',
        type: 'image',
        data: {
          url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=1000&auto=format&fit=crop&q=80',
          alt: 'Bienvenida',
          width: '100%',
          maxWidth: '100%',
          alignment: 'center',
          borderRadius: '12px',
          linkUrl: '',
          paddingTop: '0px',
          paddingBottom: '16px',
        },
      },
      {
        id: 'w-2',
        type: 'heading',
        data: {
          content: '¡Te damos la bienvenida a bordo! 🎉',
          fontSize: '26px',
          fontWeight: '800',
          color: '#0f172a',
          textAlign: 'center',
          paddingTop: '10px',
          paddingBottom: '6px',
        },
      },
      {
        id: 'w-3',
        type: 'text',
        data: {
          content: 'Estamos muy emocionados de tenerte con nosotros. Para comenzar de la forma más rápida y sacar el máximo provecho, te preparamos un tutorial en video de solo 3 minutos.',
          fontSize: '15px',
          fontWeight: '400',
          color: '#475569',
          textAlign: 'center',
          lineHeight: '1.6',
          paddingTop: '4px',
          paddingBottom: '18px',
        },
      },
      {
        id: 'w-4',
        type: 'youtube',
        data: {
          url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
          title: 'Guía de Inicio Rápido (3 Minutos)',
          caption: 'Aprende los conceptos básicos y cómo personalizar tu primer envío.',
          buttonText: 'Reproducir Guía ▶',
          cardBackground: '#1e293b',
          textColor: '#ffffff',
          borderRadius: '12px',
          paddingTop: '8px',
          paddingBottom: '20px',
        },
      },
      {
        id: 'w-5',
        type: 'button',
        data: {
          text: 'Ir a mi Panel de Control',
          url: 'https://example.com',
          backgroundColor: '#2563eb',
          textColor: '#ffffff',
          borderRadius: '8px',
          fontSize: '16px',
          fontWeight: '600',
          paddingX: '30px',
          paddingY: '12px',
          alignment: 'center',
          fullWidth: false,
        },
      },
      {
        id: 'w-6',
        type: 'divider',
        data: {
          color: '#e2e8f0',
          thickness: '1px',
          style: 'solid',
          paddingTop: '24px',
          paddingBottom: '16px',
          width: '100%',
        },
      },
      {
        id: 'w-7',
        type: 'text',
        data: {
          content: '¿Tienes alguna duda o necesitas ayuda? Responde directamente a este correo y nuestro equipo te asistirá con gusto.',
          fontSize: '13px',
          fontWeight: '400',
          color: '#94a3b8',
          textAlign: 'center',
          lineHeight: '1.5',
          paddingTop: '4px',
          paddingBottom: '0px',
        },
      },
    ],
  },
  {
    id: 'minimal-newsletter',
    name: 'Boletín Minimalista',
    description: 'Diseño limpio con cajas de contenido destacado, imágenes y tipografía cuidada.',
    globalSettings: {
      backgroundColor: '#f1f5f9',
      contentBackgroundColor: '#ffffff',
      contentWidth: '600px',
      borderRadius: '14px',
      textColor: '#1e293b',
      padding: '32px',
    },
    blocks: [
      {
        id: 'm-1',
        type: 'heading',
        data: {
          content: 'Boletín Semanal #42',
          fontSize: '24px',
          fontWeight: '800',
          color: '#0f172a',
          textAlign: 'left',
          paddingTop: '0px',
          paddingBottom: '4px',
        },
      },
      {
        id: 'm-2',
        type: 'text',
        data: {
          content: 'Edición del 13 de Septiembre • 5 minutos de lectura',
          fontSize: '13px',
          fontWeight: '500',
          color: '#64748b',
          textAlign: 'left',
          lineHeight: '1.4',
          paddingTop: '0px',
          paddingBottom: '16px',
        },
      },
      {
        id: 'm-3',
        type: 'divider',
        data: {
          color: '#e2e8f0',
          thickness: '2px',
          style: 'solid',
          paddingTop: '0px',
          paddingBottom: '16px',
          width: '100%',
        },
      },
      {
        id: 'm-4',
        type: 'box',
        data: {
          backgroundColor: '#eff6ff',
          borderRadius: '10px',
          borderWidth: '1px',
          borderColor: '#bfdbfe',
          borderStyle: 'solid',
          paddingTop: '16px',
          paddingBottom: '16px',
          paddingLeft: '20px',
          paddingRight: '20px',
          children: [
            {
              id: 'box-m-1',
              type: 'heading',
              data: {
                content: 'Tendencia de la semana: Interactividad en Emails',
                fontSize: '17px',
                fontWeight: '700',
                color: '#1e40af',
                textAlign: 'left',
                paddingTop: '0px',
                paddingBottom: '6px',
              },
            },
            {
              id: 'box-m-2',
              type: 'text',
              data: {
                content: 'Cada vez más empresas están apostando por previews con miniaturas de alta definición y botones directos a plataformas como YouTube para evitar las restricciones de los clientes de correo tradicionales.',
                fontSize: '14px',
                fontWeight: '400',
                color: '#1e3a8a',
                textAlign: 'left',
                lineHeight: '1.6',
                paddingTop: '0px',
                paddingBottom: '0px',
              },
            },
          ],
        },
      },
      {
        id: 'm-5',
        type: 'spacer',
        data: {
          height: '20px',
        },
      },
      {
        id: 'm-6',
        type: 'button',
        data: {
          text: 'Leer edición completa online',
          url: 'https://example.com',
          backgroundColor: '#0f172a',
          textColor: '#ffffff',
          borderRadius: '8px',
          fontSize: '14px',
          fontWeight: '600',
          paddingX: '24px',
          paddingY: '10px',
          alignment: 'left',
          fullWidth: false,
        },
      },
    ],
  },
];
